# Generated by Django 4.2 on 2023-05-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customer_name_alter_customer_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.CharField(default='', max_length=200),
        ),
    ]
