# Generated by Django 4.2 on 2023-05-02 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_commentsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentsection',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
