# Generated by Django 4.2 on 2023-05-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_commentsection_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentsection',
            old_name='user',
            new_name='name',
        ),
    ]
