# Generated by Django 4.2 on 2023-05-02 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_user_commentsection_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='comment',
            field=models.CharField(default='', max_length=2000, unique=True),
        ),
    ]
