# Generated by Django 4.2 on 2023-05-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_commentsection_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsection',
            name='comment',
            field=models.CharField(default='', max_length=2000),
        ),
    ]
