# Generated by Django 4.2 on 2023-05-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_commentsection_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='token',
        ),
    ]
